name: attendance_management_system_ams
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  cupertino_icons: ^1.0.6
  community_material_icon: ^5.4.55
  font_awesome_flutter: ^10.7.0
  gettext: ^1.2.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_analytics: ^10.10.7
  flutter_launcher_icons: ^0.13.1
<<<<<<< Updated upstream
=======
  google_nav_bar: ^5.0.6
  
>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/amslogo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/logo/
