// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQxQdnmUlp4W5D3ARZbbHxk-C28tpc8ck',
    appId: '1:301973610015:web:615a559ee7d547a1bb3f2a',
    messagingSenderId: '301973610015',
    projectId: 'attendance-management-sy-5fbf6',
    authDomain: 'attendance-management-sy-5fbf6.firebaseapp.com',
    databaseURL: 'https://attendance-management-sy-5fbf6-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-management-sy-5fbf6.appspot.com',
    measurementId: 'G-6FXCGRW3Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqVtuUi4Ea3NrtxldHcmh7x_69XRsIAoA',
    appId: '1:301973610015:android:d7fe4065cd8f943bbb3f2a',
    messagingSenderId: '301973610015',
    projectId: 'attendance-management-sy-5fbf6',
    databaseURL: 'https://attendance-management-sy-5fbf6-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-management-sy-5fbf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPKG29xnTFQdp1aiBbDyxGz5SiWx_kJQc',
    appId: '1:301973610015:ios:62de8a140a16271bbb3f2a',
    messagingSenderId: '301973610015',
    projectId: 'attendance-management-sy-5fbf6',
    databaseURL: 'https://attendance-management-sy-5fbf6-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-management-sy-5fbf6.appspot.com',
    iosBundleId: 'com.example.attendanceManagementSystemAms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPKG29xnTFQdp1aiBbDyxGz5SiWx_kJQc',
    appId: '1:301973610015:ios:62de8a140a16271bbb3f2a',
    messagingSenderId: '301973610015',
    projectId: 'attendance-management-sy-5fbf6',
    databaseURL: 'https://attendance-management-sy-5fbf6-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-management-sy-5fbf6.appspot.com',
    iosBundleId: 'com.example.attendanceManagementSystemAms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQxQdnmUlp4W5D3ARZbbHxk-C28tpc8ck',
    appId: '1:301973610015:web:8d6cb9aa92242b8cbb3f2a',
    messagingSenderId: '301973610015',
    projectId: 'attendance-management-sy-5fbf6',
    authDomain: 'attendance-management-sy-5fbf6.firebaseapp.com',
    databaseURL: 'https://attendance-management-sy-5fbf6-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-management-sy-5fbf6.appspot.com',
    measurementId: 'G-BC4FBGZMTW',
  );

}